### ISSUE TITLE
Does this work on Windows machine?

### ISSUE THREAD

**Issue by Moon-developer** [Sivecano/brickAprint#1]
I tried setting this up and getting the following error:
```
where do you want to store the all the files? : ./temp
downloading parts...
downloaded 6 parts
downloaded parts
converting parts...
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\brickAprint\main.py", line 89, in <module>
    get_set(set)
  File "C:\Users\user\PycharmProjects\brickAprint\main.py", line 53, in get_set
    convert_to_stl(numbers, stldir)
  File "C:\Users\user\PycharmProjects\brickAprint\main.py", line 12, in convert_to_stl
    subprocess.check_call(['./ldraw2stl/bin/dat2stl',
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
```
Would really like to use this as printabrick has been offline for awhile now.

**Comment by Sivecano** [comment]
I'm not quite sure. you should check that perl is installed. and perhaps change all the paths to use "\" instead of "/". you might even need to change the shebang on the ldraw2stl script. but if you don't want to have to mess around with it WSL might be the best solution for you. 
I think I'll push some changes to make it a bit more operating system-agnostic but I can't really test it.

**Comment by Sivecano** [comment]
ok, I changed some path separators

**Comment by Sivecano** [comment]
if you have a mac you can try running it on there. but this code was originally made to work on linux.
